name    'fhrbek-wpl'
version '0.1.0'
source 'UNKNOWN'
author 'fhrbek'
license 'Apache License, Version 2.0'
summary 'UNKNOWN'
description 'UNKNOWN'
project_page 'UNKNOWN'

dependency 'puppetlabs/apache', '>= 0.9.0'
dependency 'yguenane/tomcat6', '>= 0.0.5'
