name    'fhrbek-wpl'
version '0.1.0'
source 'UNKNOWN'
author 'fhrbek'
license 'Apache License, Version 2.0'
summary 'UNKNOWN'
description 'UNKNOWN'
project_page 'UNKNOWN'

dependency 'puppetlabs/apache', '>= 0.9.0'
dependency 'puppetlabs/java', '>= 1.4.2'
dependency 'puppetlabs/tomcat', '>= 1.3.2'
dependency 'puppetlabs/postgresql', '>= 4.6.0'
dependency 'stahma/epel', '>= 1.1.1'
dependency 'bashtoni/timezone', '>= 1.0.0'
